image: docker:git
 
services:
- docker:dind
 
variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  CONTAINER_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  dockerTag: '$CI_BUILD_REF'
 
before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
stages:
  - build and stage
  - test
 
job 1:
  stage: build and stage
  script:
   - docker build -t $CONTAINER_IMAGE .
   - docker push $CONTAINER_IMAGE

job 2:
  stage: test
  script:
  # pull build image
  - docker pull $CONTAINER_IMAGE
  # start the previously built container
  - docker run -d $CONTAINER_IMAGE ping -c 20 127.0.0.1
  # Print logs
  - docker logs $(docker ps --latest --quiet)
  only:
  - master