image: node:latest

cache:
  paths:
  - node_modules/

test:
  script:
   - npm install
   - npm run test

variables:
  IMAGE: john/node

services:
  - docker:dind

build-image:
  stage: build
  image: docker
  before_script: []
  script:
    - docker build -t $IMAGE .
    - docker run -p 49160:8080 -d john/node
  tags:
    - docker

test-image:
  stage: test
  script:
    - echo "App test CURL"
    - sleep 45
    - curl -i http://localhost:49160/status
    - echo "content"
    - exit 0