image: docker:latest

variables:
  dockerTag: '$CI_BUILD_REF'
  DOCKER_REPO: customregistry
  IMAGE_BASE_NAME: node
  IMAGE: $EVISTA_DOCKER_REPO/$IMAGE_BASE_NAME:$CI_BUILD_REF
  CONTAINER_NAME: 'john-node-pipeline'
  

before_script:
- echo $dockerTag

build:
  type: build
  tags:
  - docker-in-docker-pure-builder
  script:
  # build test images
  - docker build -t $IMAGE .
  only:
  - master

services:
  - docker:dind

test:
  type: test
  variables:
    ERROR_PATH: /tmp/example_pipeline_testresults  
  script:
  # created directory for errored pages
  - mkdir -p ${ERROR_PATH} || true
   # start the previously built container
  - docker run -d --add-host 'localhost localhost.localdomain localtest:127.0.0.1' -v ${ERROR_PATH}:/app/tests/_output --name ${CONTAINER_NAME} ${IMAGE}
  # actually run tests
  - docker exec ${CONTAINER_NAME} curl -i http://localhost:49160/status
  only:
  - master
