image: node:latest

cache:
  paths:
  - node_modules/

test:
  script:
   - npm install
   - npm run test

variables:
  IMAGE: john/node
  DOCKER_HOST: tcp://docker:49160

services:
  - docker:dind

build-image:
  stage: build
  image: docker
  before_script: []
  script:
    - docker build -t $IMAGE .
    - docker run -p 49160:8080 -d john/node
    - apk update && apk add curl curl-dev bash
    - echo "App test CURL"
    - sleep 10
    - curl -i http://localhost:49160/status
    - echo "content"
    - exit 0
  tags:
    - docker
