image: node:latest

cache:
  paths:
  - node_modules/

test:lint:
  script:
    - npm run lint

test:vulnerabilities:
  script:
    - npm run vuln-test

test:
  script:
   - npm install
   - npm run test

variables:
  IMAGE: john/node
  DOCKER_HOST: tcp://localhost:2375

services:
  - docker:dind

build-image:
  stage: build
  image: docker
  before_script: []
  script:
    - export DOCKER_HOST="tcp://localhost:2375"
    - docker build -t $IMAGE .
    - docker push $IMAGE
  tags:
    - docker